#! /bin/bash

nasm bf.asm -o bf.bin
echo "section .blah" | nasm -felf64 -o empty.o /dev/stdin
objcopy --add-section .text=bf.bin empty.o bf.o
objcopy --remove-section .blah bf.o
ld -T link.ld -N -o bf bf.o
rm bf.bin bf.o empty.o
